FROM docker.io/debian:bookworm-slim

RUN useradd --system --no-create-home --shell /usr/sbin/nologin gazette && \
	apt-get update -y && \
	apt-get -y install default-jre-headless curl ca-certificates && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

# Install Apache Tika (updated to latest version)
RUN curl -o /tika-server.jar https://dlcdn.apache.org/tika/3.2.2/tika-server-standard-3.2.2.jar && \
	chmod 755 /tika-server.jar

USER gazette
EXPOSE 9998

CMD ["java", "-jar", "/tika-server.jar", "--host", "0.0.0.0"]
