FROM docker.io/debian

RUN useradd --system --no-create-home --shell /usr/sbin/nologin gazette && \
	apt-get update -y && \
	apt-get -y install default-jre curl && \
	apt-get clean

# install Apache Tika
RUN curl -o /tika-server.jar https://dlcdn.apache.org/tika/2.9.2/tika-server-standard-2.9.2.jar && \
	chmod 755 /tika-server.jar

USER gazette
EXPOSE 9998

CMD java -jar /tika-server.jar
