FROM docker.io/debian

RUN adduser --system gazette && \
	apt-get update -y && \
	apt-get -y install default-jre curl && \
	apt-get clean

# install Apache Tika
RUN curl -o /tika-server.jar http://archive.apache.org/dist/tika/tika-server-1.24.1.jar && \
	chmod 755 /tika-server.jar

USER gazette
EXPOSE 9998

CMD java -jar /tika-server.jar
