apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: querido-diario-elasticsearch
spec:
  version: 8.10.2
  http:
    tls:
      selfSignedCertificate:
        # TLS não deve ser desabilitado em produção. Isso eh feito aqui para 
        # facilitar o ambiente de desenvolvimento.
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
